/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DISKA
 */
import javax.swing.JOptionPane;
import java.awt.Color;

public class login_mahasiswa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login_mahasiswa.class.getName());

    /**
     * Creates new form login_mahasiswa
     */
    public login_mahasiswa() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        jPanel1.setBackground(new Color(0, 0, 51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icast = new javax.swing.JLabel();
        icast1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        astlbl = new javax.swing.JLabel();
        iclbl = new javax.swing.JLabel();
        icastedu = new javax.swing.JLabel();
        nimlbl = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        nimfield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        lupapasswordbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        icast.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        icast.setForeground(new java.awt.Color(0, 102, 204));
        icast.setText("ICAST");

        icast1.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        icast1.setForeground(new java.awt.Color(0, 102, 204));
        icast1.setText("ICAST");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        astlbl.setFont(new java.awt.Font("Sans Serif Collection", 1, 40)); // NOI18N
        astlbl.setForeground(new java.awt.Color(255, 102, 102));
        astlbl.setText("AST");
        jPanel1.add(astlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 28, -1, 41));

        iclbl.setFont(new java.awt.Font("Sans Serif Collection", 1, 40)); // NOI18N
        iclbl.setForeground(new java.awt.Color(0, 102, 204));
        iclbl.setText("IC");
        jPanel1.add(iclbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 28, -1, 41));

        icastedu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        icastedu.setForeground(new java.awt.Color(255, 255, 255));
        icastedu.setText("icast.edu");
        jPanel1.add(icastedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 75, -1, -1));

        nimlbl.setForeground(new java.awt.Color(255, 255, 255));
        nimlbl.setText("NIM :");
        jPanel1.add(nimlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 158, 60, -1));

        passwordlbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordlbl.setText("Password :");
        jPanel1.add(passwordlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 192, 60, -1));

        nimfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimfieldActionPerformed(evt);
            }
        });
        jPanel1.add(nimfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 155, 200, -1));

        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        jPanel1.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 189, 200, -1));

        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 240, -1, -1));

        lupapasswordbutton.setText("Lupa Password");
        lupapasswordbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lupapasswordbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(lupapasswordbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 240, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>\nYang perlu diperhatikan:<br>\n1. Lakukan Registrasi Ulang sebelum masa Registrasi Matakuliah dibuka untuk menghindari antrian.<br>\n2. Lakukan Pembayaran Uang Kuliah sebelum jatuh tempo pembayaran berakhir.<br>\n3. Segera lakukan pembayaran Pelunasan Uang Kuliah sebelum Masa Kuliah berakhir.<br>\n4. Lakukan Pembayaran Uang Kuliah yang terkonfirmasi pada site ICAST atau Bank Online.<br>\n5. Hindari melakukan akses site ICAST menggunakan perangkat berbeda secara bersamaan.<br>\n6. Perhatikan Jadwal Registrasi Ulang dan Jadwal Registrasi Matakuliah Anda.\n</html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 301, 483, 195));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        String input = nimfield.getText().trim();
        String pass = new String(passwordfield.getPassword());

        controller.auth_controller auth = new controller.auth_controller();

        // 1. Try Mahasiswa
        model.model_mahasiswa mhs = auth.loginMahasiswa(input, pass);
        if (mhs != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil (Mahasiswa)!");
            mahasiswa_home home = new mahasiswa_home();
            home.setMahasiswa(mhs);
            home.setVisible(true);
            this.dispose();
            return;
        }

        // 2. Try Dosen
        model.model_dosen dosen = auth.loginDosen(input, pass);
        if (dosen != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil (Dosen)!");
            dosen_home home = new dosen_home();
            home.setVisible(true);
            this.dispose();
            return;
        }

        // 3. Try Admin
        model.model_super_admin admin = auth.loginAdmin(input, pass);
        if (admin != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil (Admin)!");
            new super_admin_home().setVisible(true);
            this.dispose();
            return;
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Login Gagal! Gunakan: 12345, D001, atau admin");
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void lupapasswordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lupapasswordbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lupapasswordbuttonActionPerformed

    private void nimfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimfieldActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(login_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login_mahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel astlbl;
    private javax.swing.JLabel icast;
    private javax.swing.JLabel icast1;
    private javax.swing.JLabel icastedu;
    private javax.swing.JLabel iclbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JButton lupapasswordbutton;
    private javax.swing.JTextField nimfield;
    private javax.swing.JLabel nimlbl;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel passwordlbl;
    // End of variables declaration//GEN-END:variables
}
