/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DISKA
 */
public class mahasiswa_registrasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mahasiswa_registrasi.class.getName());

    /**
     * Creates new form mahasiswa_registrasi
     */
    public mahasiswa_registrasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        astlbl = new javax.swing.JLabel();
        iclbl = new javax.swing.JLabel();
        icastedu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        homebutton = new javax.swing.JButton();
        regisbutton = new javax.swing.JButton();
        jadwalbutton = new javax.swing.JButton();
        regismatkullabal = new javax.swing.JLabel();
        logoutbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        regismatkultable = new javax.swing.JTable();
        astlbl1 = new javax.swing.JLabel();
        iclbl1 = new javax.swing.JLabel();
        icastedu1 = new javax.swing.JLabel();
        kartustudibutton = new javax.swing.JButton();

        astlbl.setFont(new java.awt.Font("Sans Serif Collection", 1, 40)); // NOI18N
        astlbl.setForeground(new java.awt.Color(255, 102, 102));
        astlbl.setText("AST");

        iclbl.setFont(new java.awt.Font("Sans Serif Collection", 1, 40)); // NOI18N
        iclbl.setForeground(new java.awt.Color(0, 102, 204));
        iclbl.setText("IC");

        icastedu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        icastedu.setForeground(new java.awt.Color(255, 255, 255));
        icastedu.setText("icast.edu");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));

        homebutton.setText("Home");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });

        regisbutton.setText("Registrasi");
        regisbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisbuttonActionPerformed(evt);
            }
        });

        jadwalbutton.setText("JadwalKuliah");
        jadwalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalbuttonActionPerformed(evt);
            }
        });

        regismatkullabal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regismatkullabal.setForeground(new java.awt.Color(255, 255, 255));
        regismatkullabal.setText("Registrasi Mata Kuliah");

        logoutbutton.setText("Log Out");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        regismatkultable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Matakuliah", "Nama Matakuliah", "Dosen Pengampu", "Hari", "Jam", "Ambil Kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(regismatkultable);

        astlbl1.setFont(new java.awt.Font("Sans Serif Collection", 1, 40)); // NOI18N
        astlbl1.setForeground(new java.awt.Color(255, 102, 102));
        astlbl1.setText("AST");

        iclbl1.setFont(new java.awt.Font("Sans Serif Collection", 1, 40)); // NOI18N
        iclbl1.setForeground(new java.awt.Color(0, 102, 204));
        iclbl1.setText("IC");

        icastedu1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        icastedu1.setForeground(new java.awt.Color(255, 255, 255));
        icastedu1.setText("icast.edu");

        kartustudibutton.setText("Kartu Studi");
        kartustudibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartustudibuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutbutton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jadwalbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regisbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kartustudibutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regismatkullabal)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(iclbl1)
                        .addGap(6, 6, 6)
                        .addComponent(astlbl1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(icastedu1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iclbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(astlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(icastedu1)
                .addGap(64, 64, 64)
                .addComponent(regismatkullabal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(homebutton)
                        .addGap(18, 18, 18)
                        .addComponent(regisbutton)
                        .addGap(18, 18, 18)
                        .addComponent(kartustudibutton)
                        .addGap(18, 18, 18)
                        .addComponent(jadwalbutton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(logoutbutton)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regisbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regisbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void kartustudibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartustudibuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kartustudibuttonActionPerformed

    private void jadwalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadwalbuttonActionPerformed

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mahasiswa_registrasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel astlbl;
    private javax.swing.JLabel astlbl1;
    private javax.swing.JButton homebutton;
    private javax.swing.JLabel icastedu;
    private javax.swing.JLabel icastedu1;
    private javax.swing.JLabel iclbl;
    private javax.swing.JLabel iclbl1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jadwalbutton;
    private javax.swing.JButton kartustudibutton;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton regisbutton;
    private javax.swing.JLabel regismatkullabal;
    private javax.swing.JTable regismatkultable;
    // End of variables declaration//GEN-END:variables
}
