/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DISKA
 */
public class mahasiswa_home extends javax.swing.JFrame {
    // variable buat simpen user yg login
    private model.model_mahasiswa currentUser;

    // method buat nerima data dari login
    public void setMahasiswa(model.model_mahasiswa mhs) {
        this.currentUser = mhs;
        // Update the labels on screen (Optional, but looks nice)
        // homelabel.setText("Hi, " + mhs.getNama()); 
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mahasiswa_home.class.getName());

    /**
     * Creates new form mahasiswa_home
     */
    public mahasiswa_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homebutton = new javax.swing.JButton();
        regisbutton = new javax.swing.JButton();
        jadwalbutton = new javax.swing.JButton();
        homelabel = new javax.swing.JLabel();
        homemenulabel = new javax.swing.JLabel();
        logoutbutton = new javax.swing.JButton();
        astlbl = new javax.swing.JLabel();
        iclbl = new javax.swing.JLabel();
        icastedu = new javax.swing.JLabel();
        kartustudibutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));

        homebutton.setText("Home");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });

        regisbutton.setText("Registrasi");
        regisbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisbuttonActionPerformed(evt);
            }
        });

        jadwalbutton.setText("JadwalKuliah");
        jadwalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalbuttonActionPerformed(evt);
            }
        });

        homelabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homelabel.setForeground(new java.awt.Color(255, 255, 255));
        homelabel.setText("Home");

        homemenulabel.setForeground(new java.awt.Color(255, 255, 255));
        homemenulabel.setText("Selamat datang Mahasiswa dalam sistem ICAST");

        logoutbutton.setText("Log Out");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        astlbl.setFont(new java.awt.Font("Sans Serif Collection", 1, 40)); // NOI18N
        astlbl.setForeground(new java.awt.Color(255, 102, 102));
        astlbl.setText("AST");

        iclbl.setFont(new java.awt.Font("Sans Serif Collection", 1, 40)); // NOI18N
        iclbl.setForeground(new java.awt.Color(0, 102, 204));
        iclbl.setText("IC");

        icastedu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        icastedu.setForeground(new java.awt.Color(255, 255, 255));
        icastedu.setText("icast.edu");

        kartustudibutton.setText("Kartu Studi");
        kartustudibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartustudibuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(iclbl)
                                .addGap(6, 6, 6)
                                .addComponent(astlbl))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(icastedu))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jadwalbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regisbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutbutton)
                            .addComponent(kartustudibutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homemenulabel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(astlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(icastedu)
                .addGap(64, 64, 64)
                .addComponent(homelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(homebutton)
                        .addGap(18, 18, 18)
                        .addComponent(regisbutton)
                        .addGap(18, 18, 18)
                        .addComponent(kartustudibutton))
                    .addComponent(homemenulabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jadwalbutton)
                .addGap(86, 86, 86)
                .addComponent(logoutbutton)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regisbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisbuttonActionPerformed
    mahasiswa_registrasi page = new mahasiswa_registrasi();
    page.setMahasiswa(this.currentUser);
    page.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_regisbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void kartustudibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartustudibuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kartustudibuttonActionPerformed

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
    mahasiswa_home home = new mahasiswa_home();
    home.setMahasiswa(this.currentUser); // Go back home with data
    home.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_homebuttonActionPerformed

    private void jadwalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalbuttonActionPerformed
        mahasiswa_jadwalkuliah page = new mahasiswa_jadwalkuliah();
        page.setMahasiswa(this.currentUser); // pass user data lagi
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jadwalbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mahasiswa_home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel astlbl;
    private javax.swing.JButton homebutton;
    private javax.swing.JLabel homelabel;
    private javax.swing.JLabel homemenulabel;
    private javax.swing.JLabel icastedu;
    private javax.swing.JLabel iclbl;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jadwalbutton;
    private javax.swing.JButton kartustudibutton;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton regisbutton;
    // End of variables declaration//GEN-END:variables
}
