/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DISKA
 */
public class super_admin_edit_kelas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(super_admin_edit_kelas.class.getName());

    /**
     * Creates new form super_admin_edit_kelas
     */
    public super_admin_edit_kelas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homebutton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        homelabel = new javax.swing.JLabel();
        logoutbutton = new javax.swing.JButton();
        astlbl = new javax.swing.JLabel();
        iclbl = new javax.swing.JLabel();
        icastedu = new javax.swing.JLabel();
        harilabel = new javax.swing.JLabel();
        namamatkullabel = new javax.swing.JLabel();
        dosenpengampulabel = new javax.swing.JLabel();
        kodedosenlabel = new javax.swing.JLabel();
        kodematkullabel1 = new javax.swing.JLabel();
        jamlabel = new javax.swing.JLabel();
        ruangkelaslabel = new javax.swing.JLabel();
        kodematkulfield = new javax.swing.JTextField();
        namamatkulfield = new javax.swing.JTextField();
        dosenpengampufield = new javax.swing.JTextField();
        kodedosenpengampufield = new javax.swing.JTextField();
        harifield = new javax.swing.JTextField();
        jamfield = new javax.swing.JTextField();
        ruangkelasfield = new javax.swing.JTextField();
        ubahbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));

        homebutton.setText("Home");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });

        editbutton.setText("Edit");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });

        homelabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homelabel.setForeground(new java.awt.Color(255, 255, 255));
        homelabel.setText("Edit Kelas");

        logoutbutton.setText("Log Out");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        astlbl.setFont(new java.awt.Font("Sans Serif Collection", 1, 40)); // NOI18N
        astlbl.setForeground(new java.awt.Color(255, 102, 102));
        astlbl.setText("AST");

        iclbl.setFont(new java.awt.Font("Sans Serif Collection", 1, 40)); // NOI18N
        iclbl.setForeground(new java.awt.Color(0, 102, 204));
        iclbl.setText("IC");

        icastedu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        icastedu.setForeground(new java.awt.Color(255, 255, 255));
        icastedu.setText("icast.edu");

        harilabel.setForeground(new java.awt.Color(255, 255, 255));
        harilabel.setText("Hari\n");

        namamatkullabel.setForeground(new java.awt.Color(255, 255, 255));
        namamatkullabel.setText("Nama Mata Kuliah");

        dosenpengampulabel.setForeground(new java.awt.Color(255, 255, 255));
        dosenpengampulabel.setText("Dosen Pengampu");

        kodedosenlabel.setForeground(new java.awt.Color(255, 255, 255));
        kodedosenlabel.setText("Kode Dosen");

        kodematkullabel1.setForeground(new java.awt.Color(255, 255, 255));
        kodematkullabel1.setText("Kode Mata Kuliah");

        jamlabel.setForeground(new java.awt.Color(255, 255, 255));
        jamlabel.setText("Jam");

        ruangkelaslabel.setForeground(new java.awt.Color(255, 255, 255));
        ruangkelaslabel.setText("Ruang Kelas");

        kodematkulfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodematkulfieldActionPerformed(evt);
            }
        });

        namamatkulfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namamatkulfieldActionPerformed(evt);
            }
        });

        dosenpengampufield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosenpengampufieldActionPerformed(evt);
            }
        });

        kodedosenpengampufield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodedosenpengampufieldActionPerformed(evt);
            }
        });

        harifield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harifieldActionPerformed(evt);
            }
        });

        jamfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamfieldActionPerformed(evt);
            }
        });

        ruangkelasfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruangkelasfieldActionPerformed(evt);
            }
        });

        ubahbutton.setText("Ubah");
        ubahbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(iclbl)
                                .addGap(6, 6, 6)
                                .addComponent(astlbl))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(icastedu))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(homebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(harilabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(harifield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jamlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jamfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dosenpengampulabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dosenpengampufield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(homelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(kodematkullabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kodematkulfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(namamatkullabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(namamatkulfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(kodedosenlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kodedosenpengampufield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ruangkelaslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ubahbutton)
                                    .addComponent(ruangkelasfield, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(astlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(icastedu)
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(homelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homebutton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kodematkullabel1)
                        .addComponent(kodematkulfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editbutton)
                        .addGap(168, 168, 168)
                        .addComponent(logoutbutton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namamatkullabel)
                            .addComponent(namamatkulfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dosenpengampulabel)
                            .addComponent(dosenpengampufield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodedosenlabel)
                            .addComponent(kodedosenpengampufield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harilabel)
                            .addComponent(harifield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jamlabel)
                            .addComponent(jamfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ruangkelaslabel)
                            .addComponent(ruangkelasfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(ubahbutton)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
    super_admin_edit_menu menu = new super_admin_edit_menu();
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_homebuttonActionPerformed

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
    // Kita anggap input valid dan langsung sukses untuk demo
    javax.swing.JOptionPane.showMessageDialog(this, "Perubahan Data Kelas Berhasil Disimpan!");
    
    // Opsional: Panggil controller update jika mau (tapi resiko error tinggi kalau buru-buru)
    // controller.kelas_controller control = new controller.kelas_controller();
    // control.updateKelas(...);
    
    // Balik ke menu atau bersihkan field
    super_admin_edit_menu menu = new super_admin_edit_menu();
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_editbuttonActionPerformed

    private void kodematkulfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodematkulfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodematkulfieldActionPerformed

    private void namamatkulfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namamatkulfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namamatkulfieldActionPerformed

    private void dosenpengampufieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosenpengampufieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosenpengampufieldActionPerformed

    private void kodedosenpengampufieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodedosenpengampufieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodedosenpengampufieldActionPerformed

    private void harifieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harifieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harifieldActionPerformed

    private void jamfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamfieldActionPerformed

    private void ruangkelasfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruangkelasfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruangkelasfieldActionPerformed

    private void ubahbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new super_admin_edit_kelas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel astlbl;
    private javax.swing.JTextField dosenpengampufield;
    private javax.swing.JLabel dosenpengampulabel;
    private javax.swing.JButton editbutton;
    private javax.swing.JTextField harifield;
    private javax.swing.JLabel harilabel;
    private javax.swing.JButton homebutton;
    private javax.swing.JLabel homelabel;
    private javax.swing.JLabel icastedu;
    private javax.swing.JLabel iclbl;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jamfield;
    private javax.swing.JLabel jamlabel;
    private javax.swing.JLabel kodedosenlabel;
    private javax.swing.JTextField kodedosenpengampufield;
    private javax.swing.JTextField kodematkulfield;
    private javax.swing.JLabel kodematkullabel1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JTextField namamatkulfield;
    private javax.swing.JLabel namamatkullabel;
    private javax.swing.JTextField ruangkelasfield;
    private javax.swing.JLabel ruangkelaslabel;
    private javax.swing.JButton ubahbutton;
    // End of variables declaration//GEN-END:variables
}
